[package]
name = "podreplay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
podreplay_lib = {path = "../lib"}
tokio = { version = "1.14.0", features=["full"]}
hyper = { version = "0.14.15", features=["full"]}
tracing = "0.1.29"
tracing-subscriber = {version = "0.3.2", features=["env-filter"] }
serde = {version = "1.0.130", features=["derive"]}
chrono = { version = "0.4.19", features = ["serde"] }
reqwest = "0.11.6"
axum = {version = "0.3.4", features=["headers"]}
thiserror = "1.0.30"
chronoutil = "0.2.3"
sqlx = {git = "https://github.com/tgecho/sqlx", branch = "sqlite-datetime-utc", features=["sqlite", "chrono", "macros", "migrate", "runtime-tokio-rustls"]}
headers = "0.3.5"
regex = "1.5.4"
lazy_static = "1.4.0"
tower = "0.4.11"
tower-http = { version = "0.1.2", features = ["trace"] }
color-eyre = "0.5.11"
reqwest-tracing = "0.1.3"
reqwest-middleware = "0.1.2"

[dev-dependencies]
mockito = "0.30.0"
tracing-test = {git = "https://github.com/tgecho/tracing-test", branch = "trace-all"}
pretty_assertions = "1.0.0"

[features]
