[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
podreplay_lib = {path = "../lib"}
tokio = { version = "1.12.0", features=["full"]}
hyper = { version = "0.14.13", features=["full"]}
tracing = "0.1.29"
tracing-subscriber = "0.3.0"
serde = {version = "1.0.130", features=["derive"]}
chrono = { version = "0.4.19", features = ["serde"] }
reqwest = "0.11.6"
axum = {version = "0.2.8", features=["headers"]}
thiserror = "1.0.30"
chronoutil = "0.2.3"
sqlx = {path = "../../forks/sqlx", features=["sqlite", "chrono", "macros", "migrate", "runtime-tokio-rustls"]}
headers = "0.3.5"
regex = "1.5.4"
lazy_static = "1.4.0"

[features]
