name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
env:
  DOCKER_BUILDKIT: 1
jobs:
  browser-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
        working-directory: ui
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
        working-directory: ui
      - name: Build Docker image
        run: docker buildx build --tag podreplay .
      - name: Run Playwright tests
        run: docker version && pnpm exec playwright test
        working-directory: ui
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: ui/playwright-report/
          retention-days: 30
