name: Server

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: sqlite://./test.sqlite

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        run: |
          sqlx database create
          sqlx migrate run
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
