name: Server

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run
        run: |
          export DATABASE_URL="sqlite://$GITHUB_WORKSPACE/test.sqlite"
          cargo install sqlx-cli --no-default-features --features sqlite,rustls
          sqlx database create
          sqlx migrate run
          cargo build
          cargo test
